In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Titanic.csv')

In [3]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
df.drop(['PassengerId','Name','Ticket'],axis=1, inplace=True)

In [5]:
def drop_columns(df,columns):
    return df.drop(columns=columns)

In [8]:
#from config import DROP_CLD
#from preprocess_da import drop_columns
#drop_columns(df,DROP_CLD)

In [9]:
df.dtypes

Survived      int64
Pclass        int64
Sex             str
Age         float64
SibSp         int64
Parch         int64
Fare        float64
Cabin           str
Embarked        str
dtype: object

In [10]:
dtypes = df.dtypes
df.nunique()

Survived      2
Pclass        3
Sex           2
Age          88
SibSp         7
Parch         7
Fare        248
Cabin       147
Embarked      3
dtype: int64

In [13]:
#def get_data_summary(df: pd.DataFrame)->pd.DataFrame
dtypes = df.dtypes
n_unique = df.nunique()
pd.DataFrame({"Dtypes ": dtypes, "N_unique ": n_unique})

          Dtypes   N_unique
Survived    int64          2
Pclass      int64          3
Sex           str          2
Age       float64         88
SibSp       int64          7
Parch       int64          7
Fare      float64        248
Cabin         str        147
Embarked      str          3

In [16]:

null = df.isnull().sum()
ratio = (null / df.shape[0]) * 100
pd.DataFrame({"null": null, "ratio": ratio}).T

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked
null,0.0,0.0,0.0,177.00000,0.0,0.0,0.0,687.000000,2.000000
ratio,0.0,0.0,0.0,19.86532,0.0,0.0,0.0,77.104377,0.224467

In [18]:
df = df.dropna(subset=['Embarked'])

In [19]:
df = df.drop("Cabin",axis=1)

In [ ]:
median = df["Age"].median()

np.float64(28.0)

In [22]:
df.describe

<bound method NDFrame.describe of      Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.0      1      0   7.2500        S
1           1       1  female  38.0      1      0  71.2833        C
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
886         0       2    male  27.0      0      0  13.0000        S
887         1       1  female  19.0      0      0  30.0000        S
888         0       3  female   NaN      1      2  23.4500        S
889         1       1    male  26.0      0      0  30.0000        C
890         0       3    male  32.0      0      0   7.7500        Q

[889 rows x 8 columns]>

In [23]:
cols = ["Survived","Pclass","Sex","SibSp","Parch","Embarked"]
df[cols] = df[cols].astype("category")
pd.DataFrame(df.dtypes).T

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
0,category,category,category,float64,category,category,float64,category

In [ ]:
num_cols = df.select_dtypes("number").columns
num_cols
#from config import NUM

ModuleNotFoundError: No module named 'config'

In [33]:
for col in num_cols:
    Q1= df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    #print(Q1)
    #print(Q3)
    Lower_Fence = Q1 - 1.5*IQR
    print(Lower_Fence)

-7.0
-26.7605

In [28]:
df.describe()

              Age        Fare
count  712.000000  889.000000
mean    29.642093   32.096681
std     14.492933   49.697504
min      0.420000    0.000000
25%     20.000000    7.895800
50%     28.000000   14.454200
75%     38.000000   31.000000
max     80.000000  512.329200